# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\DennisK\Desktop\Projects\AssistingLights\workspace\LightUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("color: rgb(210, 210, 210);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setStyleSheet("background-color: rgb(40, 44, 52);\n"
"\n"
"/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
"}\n"
"\n"
"/* RADIO BUTTON */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"")
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setLineWidth(0)
        self.frame_main.setObjectName("frame_main")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_main)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left = QtWidgets.QFrame(self.frame_main)
        self.frame_left.setMinimumSize(QtCore.QSize(85, 0))
        self.frame_left.setMaximumSize(QtCore.QSize(85, 16777215))
        self.frame_left.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.page_buttons = QtWidgets.QFrame(self.frame_left)
        self.page_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_buttons.setObjectName("page_buttons")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_buttons)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_button = QtWidgets.QPushButton(self.page_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_button.sizePolicy().hasHeightForWidth())
        self.home_button.setSizePolicy(sizePolicy)
        self.home_button.setMinimumSize(QtCore.QSize(85, 85))
        self.home_button.setMaximumSize(QtCore.QSize(85, 85))
        self.home_button.setAutoFillBackground(False)
        self.home_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.home_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_button.setIcon(icon)
        self.home_button.setIconSize(QtCore.QSize(58, 58))
        self.home_button.setObjectName("home_button")
        self.verticalLayout_2.addWidget(self.home_button)
        self.action_button = QtWidgets.QPushButton(self.page_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.action_button.sizePolicy().hasHeightForWidth())
        self.action_button.setSizePolicy(sizePolicy)
        self.action_button.setMinimumSize(QtCore.QSize(85, 85))
        self.action_button.setMaximumSize(QtCore.QSize(85, 85))
        self.action_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.action_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/action.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_button.setIcon(icon1)
        self.action_button.setIconSize(QtCore.QSize(50, 50))
        self.action_button.setObjectName("action_button")
        self.verticalLayout_2.addWidget(self.action_button)
        self.verticalLayout.addWidget(self.page_buttons, 0, QtCore.Qt.AlignTop)
        self.config_buttons = QtWidgets.QFrame(self.frame_left)
        self.config_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.config_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.config_buttons.setObjectName("config_buttons")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.config_buttons)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.settings_button = QtWidgets.QPushButton(self.config_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_button.sizePolicy().hasHeightForWidth())
        self.settings_button.setSizePolicy(sizePolicy)
        self.settings_button.setMinimumSize(QtCore.QSize(85, 85))
        self.settings_button.setMaximumSize(QtCore.QSize(85, 85))
        self.settings_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.settings_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_button.setIcon(icon2)
        self.settings_button.setIconSize(QtCore.QSize(64, 64))
        self.settings_button.setObjectName("settings_button")
        self.verticalLayout_3.addWidget(self.settings_button)
        self.verticalLayout.addWidget(self.config_buttons, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_2.addWidget(self.frame_left)
        self.frame_right = QtWidgets.QFrame(self.frame_main)
        self.frame_right.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_right.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right.setLineWidth(0)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.main_display_stack = QtWidgets.QStackedWidget(self.frame_right)
        self.main_display_stack.setLineWidth(0)
        self.main_display_stack.setObjectName("main_display_stack")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.home_page)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.procedure_info = QtWidgets.QFrame(self.home_page)
        self.procedure_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.procedure_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.procedure_info.setObjectName("procedure_info")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.procedure_info)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.light_controller_label = QtWidgets.QLabel(self.procedure_info)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.light_controller_label.setFont(font)
        self.light_controller_label.setObjectName("light_controller_label")
        self.verticalLayout_5.addWidget(self.light_controller_label)
        self.info_tree_view = QtWidgets.QTreeView(self.procedure_info)
        self.info_tree_view.setObjectName("info_tree_view")
        self.verticalLayout_5.addWidget(self.info_tree_view)
        self.horizontalLayout_3.addWidget(self.procedure_info)
        self.output_info = QtWidgets.QFrame(self.home_page)
        self.output_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_info.setObjectName("output_info")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.output_info)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.output_text_edit = QtWidgets.QTextEdit(self.output_info)
        self.output_text_edit.setReadOnly(True)
        self.output_text_edit.setMarkdown("")
        self.output_text_edit.setObjectName("output_text_edit")
        self.verticalLayout_6.addWidget(self.output_text_edit)
        self.horizontalLayout_3.addWidget(self.output_info)
        self.main_display_stack.addWidget(self.home_page)
        self.procedure_page = QtWidgets.QWidget()
        self.procedure_page.setObjectName("procedure_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.procedure_page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.procedure_scroll_area = QtWidgets.QScrollArea(self.procedure_page)
        self.procedure_scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.procedure_scroll_area.setFrameShadow(QtWidgets.QFrame.Plain)
        self.procedure_scroll_area.setLineWidth(0)
        self.procedure_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.procedure_scroll_area.setWidgetResizable(True)
        self.procedure_scroll_area.setObjectName("procedure_scroll_area")
        self.procedure_scroll_widgets = QtWidgets.QWidget()
        self.procedure_scroll_widgets.setGeometry(QtCore.QRect(0, 0, 157, 80))
        self.procedure_scroll_widgets.setStyleSheet("")
        self.procedure_scroll_widgets.setObjectName("procedure_scroll_widgets")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.procedure_scroll_widgets)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.procedure_sample_row = QtWidgets.QFrame(self.procedure_scroll_widgets)
        self.procedure_sample_row.setMinimumSize(QtCore.QSize(0, 80))
        self.procedure_sample_row.setMaximumSize(QtCore.QSize(16777215, 80))
        self.procedure_sample_row.setStyleSheet("")
        self.procedure_sample_row.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.procedure_sample_row.setFrameShadow(QtWidgets.QFrame.Plain)
        self.procedure_sample_row.setLineWidth(1)
        self.procedure_sample_row.setObjectName("procedure_sample_row")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.procedure_sample_row)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.procedure_sample_top_line = QtWidgets.QFrame(self.procedure_sample_row)
        self.procedure_sample_top_line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.procedure_sample_top_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.procedure_sample_top_line.setObjectName("procedure_sample_top_line")
        self.verticalLayout_9.addWidget(self.procedure_sample_top_line)
        self.procedure_sample_content = QtWidgets.QFrame(self.procedure_sample_row)
        self.procedure_sample_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.procedure_sample_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.procedure_sample_content.setObjectName("procedure_sample_content")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.procedure_sample_content)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.procedure_sample_left = QtWidgets.QFrame(self.procedure_sample_content)
        self.procedure_sample_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.procedure_sample_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.procedure_sample_left.setObjectName("procedure_sample_left")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.procedure_sample_left)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.procedure_sample_title = QtWidgets.QLabel(self.procedure_sample_left)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.procedure_sample_title.setFont(font)
        self.procedure_sample_title.setObjectName("procedure_sample_title")
        self.verticalLayout_10.addWidget(self.procedure_sample_title)
        self.procedure_sample_desc = QtWidgets.QLabel(self.procedure_sample_left)
        self.procedure_sample_desc.setObjectName("procedure_sample_desc")
        self.verticalLayout_10.addWidget(self.procedure_sample_desc)
        self.horizontalLayout_4.addWidget(self.procedure_sample_left)
        self.procedure_sample_button = QtWidgets.QPushButton(self.procedure_sample_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.procedure_sample_button.sizePolicy().hasHeightForWidth())
        self.procedure_sample_button.setSizePolicy(sizePolicy)
        self.procedure_sample_button.setMinimumSize(QtCore.QSize(70, 70))
        self.procedure_sample_button.setMaximumSize(QtCore.QSize(70, 70))
        self.procedure_sample_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.procedure_sample_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/filter.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.procedure_sample_button.setIcon(icon3)
        self.procedure_sample_button.setIconSize(QtCore.QSize(56, 56))
        self.procedure_sample_button.setObjectName("procedure_sample_button")
        self.horizontalLayout_4.addWidget(self.procedure_sample_button)
        self.verticalLayout_9.addWidget(self.procedure_sample_content)
        self.procedure_sample_bottom_line = QtWidgets.QFrame(self.procedure_sample_row)
        self.procedure_sample_bottom_line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.procedure_sample_bottom_line.setLineWidth(1)
        self.procedure_sample_bottom_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.procedure_sample_bottom_line.setObjectName("procedure_sample_bottom_line")
        self.verticalLayout_9.addWidget(self.procedure_sample_bottom_line)
        self.verticalLayout_8.addWidget(self.procedure_sample_row, 0, QtCore.Qt.AlignTop)
        self.procedure_scroll_area.setWidget(self.procedure_scroll_widgets)
        self.verticalLayout_7.addWidget(self.procedure_scroll_area)
        self.main_display_stack.addWidget(self.procedure_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.settings_page)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.how_to_info = QtWidgets.QFrame(self.settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.how_to_info.sizePolicy().hasHeightForWidth())
        self.how_to_info.setSizePolicy(sizePolicy)
        self.how_to_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.how_to_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.how_to_info.setObjectName("how_to_info")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.how_to_info)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.how_to_label = QtWidgets.QLabel(self.how_to_info)
        self.how_to_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.how_to_label.setObjectName("how_to_label")
        self.verticalLayout_12.addWidget(self.how_to_label, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_5.addWidget(self.how_to_info)
        self.sys_man_info = QtWidgets.QFrame(self.settings_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sys_man_info.sizePolicy().hasHeightForWidth())
        self.sys_man_info.setSizePolicy(sizePolicy)
        self.sys_man_info.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sys_man_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sys_man_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sys_man_info.setObjectName("sys_man_info")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.sys_man_info)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.exit_app_button = QtWidgets.QPushButton(self.sys_man_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_app_button.sizePolicy().hasHeightForWidth())
        self.exit_app_button.setSizePolicy(sizePolicy)
        self.exit_app_button.setMinimumSize(QtCore.QSize(300, 50))
        self.exit_app_button.setMaximumSize(QtCore.QSize(300, 16777215))
        self.exit_app_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"   background-color: rgb(240, 30, 30);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(220, 10, 10);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.exit_app_button.setObjectName("exit_app_button")
        self.verticalLayout_11.addWidget(self.exit_app_button, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_5.addWidget(self.sys_man_info)
        self.main_display_stack.addWidget(self.settings_page)
        self.run_page = QtWidgets.QWidget()
        self.run_page.setObjectName("run_page")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.run_page)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.run_page_header = QtWidgets.QFrame(self.run_page)
        self.run_page_header.setMinimumSize(QtCore.QSize(0, 0))
        self.run_page_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.run_page_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.run_page_header.setLineWidth(0)
        self.run_page_header.setObjectName("run_page_header")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.run_page_header)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.run_page_title = QtWidgets.QLabel(self.run_page_header)
        self.run_page_title.setObjectName("run_page_title")
        self.verticalLayout_16.addWidget(self.run_page_title)
        self.run_page_desc = QtWidgets.QLabel(self.run_page_header)
        self.run_page_desc.setObjectName("run_page_desc")
        self.verticalLayout_16.addWidget(self.run_page_desc)
        self.verticalLayout_13.addWidget(self.run_page_header)
        self.run_procedure_args_area = QtWidgets.QScrollArea(self.run_page)
        self.run_procedure_args_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.run_procedure_args_area.setFrameShadow(QtWidgets.QFrame.Plain)
        self.run_procedure_args_area.setWidgetResizable(True)
        self.run_procedure_args_area.setObjectName("run_procedure_args_area")
        self.args_scroll_area = QtWidgets.QWidget()
        self.args_scroll_area.setGeometry(QtCore.QRect(0, 0, 939, 480))
        self.args_scroll_area.setObjectName("args_scroll_area")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.args_scroll_area)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.args_select_sample_row = QtWidgets.QFrame(self.args_scroll_area)
        self.args_select_sample_row.setMinimumSize(QtCore.QSize(0, 80))
        self.args_select_sample_row.setMaximumSize(QtCore.QSize(16777215, 80))
        self.args_select_sample_row.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.args_select_sample_row.setFrameShadow(QtWidgets.QFrame.Raised)
        self.args_select_sample_row.setLineWidth(0)
        self.args_select_sample_row.setObjectName("args_select_sample_row")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.args_select_sample_row)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.args_select_sample_top_line = QtWidgets.QFrame(self.args_select_sample_row)
        self.args_select_sample_top_line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.args_select_sample_top_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.args_select_sample_top_line.setObjectName("args_select_sample_top_line")
        self.verticalLayout_19.addWidget(self.args_select_sample_top_line)
        self.args_select_main_frame = QtWidgets.QFrame(self.args_select_sample_row)
        self.args_select_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.args_select_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.args_select_main_frame.setObjectName("args_select_main_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.args_select_main_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.args_select_left_frame = QtWidgets.QFrame(self.args_select_main_frame)
        self.args_select_left_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.args_select_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.args_select_left_frame.setObjectName("args_select_left_frame")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.args_select_left_frame)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.args_select_title = QtWidgets.QLabel(self.args_select_left_frame)
        self.args_select_title.setObjectName("args_select_title")
        self.verticalLayout_20.addWidget(self.args_select_title)
        self.args_select_desc = QtWidgets.QLabel(self.args_select_left_frame)
        self.args_select_desc.setObjectName("args_select_desc")
        self.verticalLayout_20.addWidget(self.args_select_desc)
        self.horizontalLayout_8.addWidget(self.args_select_left_frame)
        self.args_select_right_frame = QtWidgets.QFrame(self.args_select_main_frame)
        self.args_select_right_frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.args_select_right_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.args_select_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.args_select_right_frame.setObjectName("args_select_right_frame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.args_select_right_frame)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.args_select_box = QtWidgets.QComboBox(self.args_select_right_frame)
        self.args_select_box.setCurrentText("")
        self.args_select_box.setObjectName("args_select_box")
        self.verticalLayout_21.addWidget(self.args_select_box)
        self.horizontalLayout_8.addWidget(self.args_select_right_frame)
        self.verticalLayout_19.addWidget(self.args_select_main_frame)
        self.args_select_sample_bottom_line = QtWidgets.QFrame(self.args_select_sample_row)
        self.args_select_sample_bottom_line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.args_select_sample_bottom_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.args_select_sample_bottom_line.setObjectName("args_select_sample_bottom_line")
        self.verticalLayout_19.addWidget(self.args_select_sample_bottom_line)
        self.verticalLayout_14.addWidget(self.args_select_sample_row)
        self.args_color_sample_row = QtWidgets.QFrame(self.args_scroll_area)
        self.args_color_sample_row.setMinimumSize(QtCore.QSize(0, 80))
        self.args_color_sample_row.setMaximumSize(QtCore.QSize(16777215, 80))
        self.args_color_sample_row.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.args_color_sample_row.setFrameShadow(QtWidgets.QFrame.Raised)
        self.args_color_sample_row.setObjectName("args_color_sample_row")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.args_color_sample_row)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.args_color_sample_bottom_line = QtWidgets.QFrame(self.args_color_sample_row)
        self.args_color_sample_bottom_line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.args_color_sample_bottom_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.args_color_sample_bottom_line.setObjectName("args_color_sample_bottom_line")
        self.verticalLayout_15.addWidget(self.args_color_sample_bottom_line)
        self.args_color_main_frame = QtWidgets.QFrame(self.args_color_sample_row)
        self.args_color_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.args_color_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.args_color_main_frame.setObjectName("args_color_main_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.args_color_main_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.args_color_left_frame = QtWidgets.QFrame(self.args_color_main_frame)
        self.args_color_left_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.args_color_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.args_color_left_frame.setLineWidth(0)
        self.args_color_left_frame.setObjectName("args_color_left_frame")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.args_color_left_frame)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.args_color_title = QtWidgets.QLabel(self.args_color_left_frame)
        self.args_color_title.setObjectName("args_color_title")
        self.verticalLayout_17.addWidget(self.args_color_title)
        self.args_color_desc = QtWidgets.QLabel(self.args_color_left_frame)
        self.args_color_desc.setLineWidth(0)
        self.args_color_desc.setObjectName("args_color_desc")
        self.verticalLayout_17.addWidget(self.args_color_desc)
        self.horizontalLayout_7.addWidget(self.args_color_left_frame)
        self.args_color_right_frame = QtWidgets.QFrame(self.args_color_main_frame)
        self.args_color_right_frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.args_color_right_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.args_color_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.args_color_right_frame.setLineWidth(0)
        self.args_color_right_frame.setObjectName("args_color_right_frame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.args_color_right_frame)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.args_color_button = QtWidgets.QPushButton(self.args_color_right_frame)
        self.args_color_button.setMinimumSize(QtCore.QSize(0, 30))
        self.args_color_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.args_color_button.setObjectName("args_color_button")
        self.verticalLayout_18.addWidget(self.args_color_button)
        self.args_color_preview = QtWidgets.QLabel(self.args_color_right_frame)
        self.args_color_preview.setObjectName("args_color_preview")
        self.verticalLayout_18.addWidget(self.args_color_preview)
        self.horizontalLayout_7.addWidget(self.args_color_right_frame)
        self.verticalLayout_15.addWidget(self.args_color_main_frame)
        self.args_color_sample_top_line = QtWidgets.QFrame(self.args_color_sample_row)
        self.args_color_sample_top_line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.args_color_sample_top_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.args_color_sample_top_line.setObjectName("args_color_sample_top_line")
        self.verticalLayout_15.addWidget(self.args_color_sample_top_line)
        self.verticalLayout_14.addWidget(self.args_color_sample_row, 0, QtCore.Qt.AlignTop)
        self.run_procedure_args_area.setWidget(self.args_scroll_area)
        self.verticalLayout_13.addWidget(self.run_procedure_args_area)
        self.run_procedure_bottom = QtWidgets.QFrame(self.run_page)
        self.run_procedure_bottom.setMinimumSize(QtCore.QSize(0, 0))
        self.run_procedure_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.run_procedure_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.run_procedure_bottom.setLineWidth(0)
        self.run_procedure_bottom.setObjectName("run_procedure_bottom")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.run_procedure_bottom)
        self.horizontalLayout_6.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.run_procedure_start_button = QtWidgets.QPushButton(self.run_procedure_bottom)
        self.run_procedure_start_button.setMinimumSize(QtCore.QSize(300, 50))
        self.run_procedure_start_button.setMaximumSize(QtCore.QSize(300, 16777215))
        self.run_procedure_start_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(35, 83, 71);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.run_procedure_start_button.setObjectName("run_procedure_start_button")
        self.horizontalLayout_6.addWidget(self.run_procedure_start_button, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_13.addWidget(self.run_procedure_bottom)
        self.main_display_stack.addWidget(self.run_page)
        self.verticalLayout_4.addWidget(self.main_display_stack)
        self.horizontalLayout_2.addWidget(self.frame_right)
        self.horizontalLayout.addWidget(self.frame_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_display_stack.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.light_controller_label.setText(_translate("MainWindow", "Light Controller"))
        self.output_text_edit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.procedure_sample_title.setText(_translate("MainWindow", "TextLabel"))
        self.procedure_sample_desc.setText(_translate("MainWindow", "TextLabel"))
        self.how_to_label.setText(_translate("MainWindow", "Glory to Theta Chi Spring 24"))
        self.exit_app_button.setText(_translate("MainWindow", "Exit Application"))
        self.run_page_title.setText(_translate("MainWindow", "TextLabel"))
        self.run_page_desc.setText(_translate("MainWindow", "TextLabel"))
        self.args_select_title.setText(_translate("MainWindow", "TextLabel"))
        self.args_select_desc.setText(_translate("MainWindow", "TextLabel"))
        self.args_color_title.setText(_translate("MainWindow", "TextLabel"))
        self.args_color_desc.setText(_translate("MainWindow", "TextLabel"))
        self.args_color_button.setText(_translate("MainWindow", "Select Color"))
        self.args_color_preview.setText(_translate("MainWindow", "TextLabel"))
        self.run_procedure_start_button.setText(_translate("MainWindow", "Start"))
import light_ui_res
